
export const COUNTRIES = [
  { name: "Vietnam", code: "VN", dial_code: "+84" },
  { name: "Australia", code: "AU", dial_code: "+61" },
  { name: "Austria", code: "AT", dial_code: "+43" },
  { name: "Belgium", code: "BE", dial_code: "+32" },
  { name: "Brazil", code: "BR", dial_code: "+55" },
  { name: "Cambodia", code: "KH", dial_code: "+855" },
  { name: "Canada", code: "CA", dial_code: "+1" },
  { name: "China", code: "CN", dial_code: "+86" },
  { name: "Denmark", code: "DK", dial_code: "+45" },
  { name: "Egypt", code: "EG", dial_code: "+20" },
  { name: "Finland", code: "FI", dial_code: "+358" },
  { name: "France", code: "FR", dial_code: "+33" },
  { name: "Germany", code: "DE", dial_code: "+49" },
  { name: "Hong Kong", code: "HK", dial_code: "+852" },
  { name: "India", code: "IN", dial_code: "+91" },
  { name: "Indonesia", code: "ID", dial_code: "+62" },
  { name: "Ireland", code: "IE", dial_code: "+353" },
  { name: "Israel", code: "IL", dial_code: "+972" },
  { name: "Italy", code: "IT", dial_code: "+39" },
  { name: "Japan", code: "JP", dial_code: "+81" },
  { name: "Laos", code: "LA", dial_code: "+856" },
  { name: "Macau", code: "MO", dial_code: "+853" },
  { name: "Malaysia", code: "MY", dial_code: "+60" },
  { name: "Mexico", code: "MX", dial_code: "+52" },
  { name: "Myanmar", code: "MM", dial_code: "+95" },
  { name: "Netherlands", code: "NL", dial_code: "+31" },
  { name: "New Zealand", code: "NZ", dial_code: "+64" },
  { name: "Norway", code: "NO", dial_code: "+47" },
  { name: "Philippines", code: "PH", dial_code: "+63" },
  { name: "Poland", code: "PL", dial_code: "+48" },
  { name: "Portugal", code: "PT", dial_code: "+351" },
  { name: "Russia", code: "RU", dial_code: "+7" },
  { name: "Saudi Arabia", code: "SA", dial_code: "+966" },
  { name: "Singapore", code: "SG", dial_code: "+65" },
  { name: "South Africa", code: "ZA", dial_code: "+27" },
  { name: "South Korea", code: "KR", dial_code: "+82" },
  { name: "Spain", code: "ES", dial_code: "+34" },
  { name: "Sweden", code: "SE", dial_code: "+46" },
  { name: "Switzerland", code: "CH", dial_code: "+41" },
  { name: "Taiwan", code: "TW", dial_code: "+886" },
  { name: "Thailand", code: "TH", dial_code: "+66" },
  { name: "Turkey", code: "TR", dial_code: "+90" },
  { name: "UAE", code: "AE", dial_code: "+971" },
  { name: "United Kingdom", code: "GB", dial_code: "+44" },
  { name: "United States", code: "US", dial_code: "+1" }
];
